# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next

class Solution:
    def add(self, l1: Optional[ListNode], l2: Optional[ListNode], carry: int) -> Optional[ListNode]:
        # Base Case: If both lists are fully traversed and there is no remaining carry,
        # we have reached the end of the addition process.
        if not l1 and not l2 and carry == 0:
            return None

        # Extract the values from the current nodes. 
        # If a list has already ended, treat its value as 0.
        v1 = l1.val if l1 else 0
        v2 = l2.val if l2 else 0

        # Calculate the new carry and the single-digit value for the current node.
        # divmod(a, b) returns (a // b, a % b). 
        # For example, divmod(15, 10) gives carry = 1, val = 5.
        # carry means do we have to carry 1 to another digit
        carry, val = divmod(v1 + v2 + carry, 10)

        # Move to the next nodes in the lists and pass the updated carry recursively.
        # If l1 or l2 is already None, pass None forward.
        next_node = self.add(
            l1.next if l1 else None,
            l2.next if l2 else None,
            carry
        )
        
        # Create the new result node with the calculated single-digit value
        # and link it to the rest of the sum generated by the recursive call.
        return ListNode(val, next_node)

    def addTwoNumbers(self, l1: Optional[ListNode], l2: Optional[ListNode]) -> Optional[ListNode]:
        # Kick off the recursive addition starting with an initial carry of 0.
        return self.add(l1, l2, 0)